In [ ]:
! pip install kaggle

In [3]:
! mkdir ~/.kaggle

In [4]:
! cp kaggle.json ~/.kaggle/

In [5]:
! chmod 600 ~/.kaggle/kaggle.json

In [7]:
!kaggle datasets download -d shivanandmn/multilabel-classification-dataset

 44% 5.00M/11.4M [00:00<00:00, 27.7MB/s]
100% 11.4M/11.4M [00:00<00:00, 41.5MB/s]


In [8]:
!unzip multilabel-classification-dataset.zip

Archive:  multilabel-classification-dataset.zip
  inflating: sample_submission.csv   
  inflating: test.csv                
  inflating: train.csv               


In [10]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [12]:
import pandas as pd

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

In [ ]:

def text_to_vectors(df, max_len=128, max_features=None, vocab_size=None):
  """
  Converts text columns in a DataFrame to vectors for neural network input.

  Args:
      df (pandas.DataFrame): DataFrame containing text columns.
      max_len (int, optional): Maximum length for padded sequences. Defaults to 100.
      max_features (int, optional): Maximum number of words to consider in the vocabulary.
                                   Overrides vocab_size if both are provided.
      vocab_size (int, optional): Size of the vocabulary to use. Defaults to None (all words).

  Returns:
      pandas.DataFrame: DataFrame with vectorized representations of text columns.
  """

  # Combine title and abstract for better representation (optional)
  text_data = df['TITLE'] + ' ' + df['ABSTRACT']

  # Tokenize text data
  tokenizer = Tokenizer(num_words=max_features if max_features else vocab_size)
  tokenizer.fit_on_texts(text_data)
  sequences = tokenizer.texts_to_sequences(text_data)

  # Pad sequences to same length
  padded_sequences = pad_sequences(sequences, maxlen=max_len)

  return padded_sequences

3

(1, 3)

In [ ]:

import pandas as pd
import numpy as np
import sys
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:

data = pd.read_csv('/content/train.csv')
text_data = data['ABSTRACT'] + ' ' + data['TITLE']

In [ ]:
data

ID                                              TITLE  \
0          1        Reconstructing Subject-Specific Effect Maps   
1          2                 Rotation Invariance Neural Network   
2          3  Spherical polyharmonics and Poisson kernels fo...   
3          4  A finite element approximation for the stochas...   
4          5  Comparative study of Discrete Wavelet Transfor...   
...      ...                                                ...   
20967  20968  Contemporary machine learning: a guide for pra...   
20968  20969  Uniform diamond coatings on WC-Co hard alloy c...   
20969  20970  Analysing Soccer Games with Clustering and Con...   
20970  20971  On the Efficient Simulation of the Left-Tail o...   
20971  20972   Why optional stopping is a problem for Bayesians   

                                                ABSTRACT  Computer Science  \
0        Predictive models allow subject-specific inf...                 1   
1        Rotation invariance and translation invarian...                 1   
2        We introduce and develop the notion of spher...                 0   
3        The stochastic Landau--Lifshitz--Gilbert (LL...                 0   
4        Fourier-transform infra-red (FTIR) spectra o...                 1   
...                                                  ...               ...   
20967    Machine learning is finding increasingly bro...                 1   
20968    Polycrystalline diamond coatings have been g...                 0   
20969    We present a new approach for identifying si...                 1   
20970    The sum of Log-normal variates is encountere...                 0   
20971    Recently, optional stopping has been a subje...                 0   

       Physics  Mathematics  Statistics  Quantitative Biology  \
0            0            0           0                     0   
1            0            0           0                     0   
2            0            1           0                     0   
3            0            1           0                     0   
4            0            0           1                     0   
...        ...          ...         ...                   ...   
20967        1            0           0                     0   
20968        1            0           0                     0   
20969        0            0           0                     0   
20970        0            1           1                     0   
20971        0            1           1                     0   

       Quantitative Finance  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0  
...                     ...  
20967                     0  
20968                     0  
20969                     0  
20970                     0  
20971                     0  

[20972 rows x 9 columns]

In [ ]:
text_data

0          Predictive models allow subject-specific inf...
1          Rotation invariance and translation invarian...
2          We introduce and develop the notion of spher...
3          The stochastic Landau--Lifshitz--Gilbert (LL...
4          Fourier-transform infra-red (FTIR) spectra o...
                               ...                        
20967      Machine learning is finding increasingly bro...
20968      Polycrystalline diamond coatings have been g...
20969      We present a new approach for identifying si...
20970      The sum of Log-normal variates is encountere...
20971      Recently, optional stopping has been a subje...
Length: 20972, dtype: object

In [ ]:
labels = data[['Computer Science', 'Physics', 'Mathematics', 'Statistics', 'Quantitative Biology', 'Quantitative Finance']]


In [ ]:
labels=np.array(labels)


In [ ]:
labels

array([[1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       ...,
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0]])

In [ ]:
vectorizer = TfidfVectorizer(max_features=5000)
vectorizer

TfidfVectorizer(max_features=5000)

In [ ]:
X = vectorizer.fit_transform(text_data)

In [69]:
X

<20972x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 1744889 stored elements in Compressed Sparse Row format>

In [ ]:
X.shape

(20972, 5000)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)


In [ ]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [68]:
X_train[:1]

array([[0., 0., 0., ..., 0., 0., 0.]])

In [39]:
X_test[5]

array([0., 0., 0., ..., 0., 0., 0.])

In [38]:


def sigmoid ( x ) :
  return 1 / (1 + np . exp ( - x ) )

def sigmoid_derivative ( x ) :
  return x * (1 - x )


class LinearNN:
    def __init__(self, n_inputs, n_outputs):
        self.weights = np.random.rand(n_inputs, n_outputs)
        self.bias = np.random.rand(n_outputs)

    def train(self, X, T, epochs, lr):
        for epoch in range(epochs):

            y_pred = self.predict(X)

            # Compute gradient
            d_weights = np.dot(X.T, (y_pred - T) * sigmoid_derivative(y_pred))
            d_bias = np.sum((y_pred - T) * sigmoid_derivative(y_pred), axis=0)


            self.weights -= lr * d_weights
            self.bias -= lr * d_bias

            if epoch % 100 == 0:
                loss = np.mean(-T * np.log(y_pred) - (1 - T) * np.log(1 - y_pred))
                print(f'Loss at epoch {epoch}: {loss}')

    def predict(self, X):
        return sigmoid(np.dot(X, self.weights) + self.bias)


model = LinearNN(X_train.shape[1], y_train.shape[1])
model.train(X_train, y_train, epochs=1000, lr=0.001)


predictions = np.round(model.predict(X_test))
accuracy = np.mean((predictions == y_test).all(axis=1))
print(f'Test Accuracy: {accuracy}')

Loss at epoch 0: 3.3594128439713473
Loss at epoch 100: 0.37332679829683185
Loss at epoch 200: 0.3186189484521711
Loss at epoch 300: 0.2888102640319848
Loss at epoch 400: 0.2704985570128011
Loss at epoch 500: 0.2579193429561593
Loss at epoch 600: 0.2485848725863637
Loss at epoch 700: 0.24127901331196358
Loss at epoch 800: 0.2353366089600577
Loss at epoch 900: 0.23036113500488603
Test Accuracy: 0.6033373063170441
